version: '3.8'

services:
  # HTTP REST API Server
  whatsapp-mcp-http:
    build: .
    container_name: whatsapp-mcp-http
    ports:
      - "8080:8080"
    environment:
      - META_ACCESS_TOKEN=${META_ACCESS_TOKEN}
      - META_PHONE_NUMBER_ID=${META_PHONE_NUMBER_ID}
      - META_BUSINESS_ACCOUNT_ID=${META_BUSINESS_ACCOUNT_ID}
      - WHATSAPP_API_VERSION=${WHATSAPP_API_VERSION:-v22.0}
      - HTTP_SERVER_HOST=0.0.0.0
      - HTTP_SERVER_PORT=8080
    command: python server_http.py
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

  # SSE Server (alternative)
  whatsapp-mcp-sse:
    build: .
    container_name: whatsapp-mcp-sse
    ports:
      - "8000:8000"
    environment:
      - META_ACCESS_TOKEN=${META_ACCESS_TOKEN}
      - META_PHONE_NUMBER_ID=${META_PHONE_NUMBER_ID}
      - META_BUSINESS_ACCOUNT_ID=${META_BUSINESS_ACCOUNT_ID}
      - WHATSAPP_API_VERSION=${WHATSAPP_API_VERSION:-v22.0}
      - MCP_SERVER_HOST=0.0.0.0
      - MCP_SERVER_PORT=8000
    command: python server_sse.py
    restart: unless-stopped
    profiles:
      - sse

networks:
  default:
    name: whatsapp-mcp-network