# Railway configuration for SSE MCP Server
[build]
builder = "DOCKERFILE"
dockerfilePath = "Dockerfile.sse"

[deploy]
startCommand = "python server_sse.py"
healthcheckPath = "/health"
healthcheckTimeout = 10
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3

[environment]
PORT = "8000"
MCP_SERVER_HOST = "0.0.0.0"
MCP_SERVER_PORT = "8000"